version: "3.8"

services:
  booking_db:
    image: postgres:14.2-alpine
    container_name: booking_db
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
