"""first name, last name user

Revision ID: 209707979561
Revises: 6990d505d671
Create Date: 2022-03-28 10:45:48.901178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209707979561'
down_revision = '6990d505d671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
