"""appointments complex reference

Revision ID: a4131e3275b6
Revises: adc71150a6e5
Create Date: 2022-03-31 23:00:49.626404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4131e3275b6'
down_revision = 'adc71150a6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_complex',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['complex_id'], ['complex.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'complex_id')
    )
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'phone')
    op.drop_table('appointment_complex')
    # ### end Alembic commands ###
