"""complex model

Revision ID: adc71150a6e5
Revises: 209707979561
Create Date: 2022-03-29 08:11:11.688307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc71150a6e5'
down_revision = '209707979561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric, nullable=True),
    sa.Column('interval', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complex_id'), 'complex', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complex_id'), table_name='complex')
    op.drop_table('complex')
    # ### end Alembic commands ###
